Test code: 추가/ 수정
Cherish-Gift/cherish-gift.github.io pull request #114
Opened 2023-05-02 14:22 UTC by BadaHertz52

수정 있는 test code
- AuthNumber

새로운 test code
- CheckBox
- InputForm
- AlertModal
- BottomNavModal
- PasswordForm

2023-05-02 18:20 UTC, sky21kr approved these changes
고생하셨습니다!

2023-05-02 19:39 UTC, Supertonian commented on src/components/CheckBox/indext.test.tsx
> +import { shallow, configure } from 'enzyme';
이거 파일명이 잘못된것 같습니다. to be `index.test.tsx`

2023-05-02 19:48 UTC, Supertonian requested changes
혹시 `yarn test`로 vitest로 해보신것 맞나요?

yarn test로 하니 에러가 발생하는데 vitest에서 import해서 사용해야 문제 발생안합니다.

ex) PasswordForm/index.test.tsx file
```

import { shallow, configure, render } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import { describe, it, vi, expect } from 'vitest';
```

2023-05-03 05:05 UTC, BadaHertz52 commented on src/components/CheckBox/indext.test.tsx
> +import { shallow, configure } from 'enzyme';
> 혹시 `yarn test`로 vitest로 해보신것 맞나요?
> 
> yarn test로 하니 에러가 발생하는데 vitest에서 import해서 사용해야 문제 발생안합니다.
> 
> ex) PasswordForm/index.test.tsx file
> 
> ```
> 
> import { shallow, configure, render } from 'enzyme';
> import Adapter from 'enzyme-adapter-react-16';
> import { describe, it, vi, expect } from 'vitest';
> ```
 
yarn run test로 진행했고, 저는 잘됐어요
![image](https://user-images.githubusercontent.com/69838872/235836267-4f106ae8-ba1a-4322-9e63-8c49be2214be.png)

2023-05-03 05:09 UTC, BadaHertz52 commented
> 혹시 `yarn test`로 vitest로 해보신것 맞나요?
> 
> yarn test로 하니 에러가 발생하는데 vitest에서 import해서 사용해야 문제 발생안합니다.
> 
> ex) PasswordForm/index.test.tsx file
> 
> ```
> 
> import { shallow, configure, render } from 'enzyme';
> import Adapter from 'enzyme-adapter-react-16';
> import { describe, it, vi, expect } from 'vitest';
> ```

yarn run test로 해보고 지금 yarn test로 해봤는데 저는 잘 됐어요 
![image](https://user-images.githubusercontent.com/69838872/235836509-28ccb8f7-6a4d-435a-bcc8-107244b30816.png)

2023-05-03 07:18 UTC, BadaHertz52 commented
vite.config.ts  파일에 test 설정해서 PasswordForm 테스트 시 오류 해결했고, LogIn 테스트 파일에 sessionStorage 관련 코드도 추가했습니다.

2023-05-03 11:05 UTC, Supertonian approved these changes

2023-05-03 11:05 UTC, merged