Fn/modal
Cherish-Gift/cherish-gift.github.io pull request #13
Opened 2023-03-13 12:15 UTC by BadaHertz52

- react-dom의 Protals을 이용해 모달창 작업을 시작했습니다.
- Protals 의 위치를 잡기 위해 index.html 에 modal element를 추가했습니다.
- 모달창 작동에 대해 테스트하기 위해서 이를 위한 페이지를 App.tsx에 따로 추가했습니다.
- 모달과 관련된 component , scss 추가했습니다.
- main.tsx에 대한 변경은 main 브런치를 고치고 나서 Reset을 넣어 준 코드가 사라져서 다시 넣었습니다. 
- 
### 모달 관련 계획
Modals 안에서 modal의 상태 변화에 따라 ModalPortal의 child 값을 변경하여 적합한 모달창이 나올 수 있도록 하고 싶습니다.
현재는 테스트 단계라서 modal에 대한 useState의 코드를 Modals 에 두었지만 다른 페이지에서 사용해서 모달창을 열 수 있도록 다른 React Node 에서 props로 전달하고 싶습니다.

2023-03-13 14:26 UTC, Supertonian commented on src/components/Modals.tsx
> +  type:undefined,
undefined를 쓰는 경우와 null을 쓰는 경우의 차이가 있나요?

2023-03-13 14:30 UTC, Supertonian commented on src/components/Modals.tsx
> +      {modal.type == undefined &&
modal.type == undefined와 아닌것인데 ? : 를 이용하는것이 더 간결해보입니다.

2023-03-13 14:34 UTC, Supertonian requested changes
전반적으로 영어 오타가 많습니다. 변수명에도 오타들이 있고 PR 메시지에서도 오타가 많아서 수정 요청드립니다.

그리고 모달을 생성한것이 여러개인데 components안에 modal이라는 폴더를 만들고 그 안에 정리하는것이 나중에도 보기 좋아보입니다.

현재 봤을 때 Modal간의 관계가 명확히 알기가 어렵습니다.

모달이라는 Base Class를 만들고 다른 모달들이 그것을 가져와 쓰는 형태가 보기 좋아보입니다.

2023-03-13 14:36 UTC, Supertonian commented
```js
import React, { useEffect } from "react";
import ReactDOM from "react-dom";

const modalRoot = document.getElementById("modal-root");

const Modal = ({ children, onClose }) => {
  useEffect(() => {
    // create a new div element
    const modalEl = document.createElement("div");

    // add a class to the div element
    modalEl.classList.add("modal");

    // add the modal element to the modal root
    modalRoot.appendChild(modalEl);

    return () => {
      // remove the modal element from the modal root when the modal is unmounted
      modalRoot.removeChild(modalEl);
    };
  }, []);

  return ReactDOM.createPortal(
    <div className="modal-overlay">
      <div className="modal-content">
        {children}
        <button className="close-button" onClick={onClose}>
          X
        </button>
      </div>
    </div>,
    document.querySelector(".modal")
  );
};

export default Modal;

```



```js
import React from "react";
import Modal from "./Modal";

const AlertModal = ({ message, onClose }) => {
  return (
    <Modal onClose={onClose}>
      <h2>Alert</h2>
      <p>{message}</p>
    </Modal>
  );
};

export default AlertModal;
```

참고용으로만 적어봅니다. 저희에 맞게 필요한 공통의 기능들을 Base로 만들고 다른 모달에서 그것을 썼으면 합니다.

@BadaHertz52 @hyunsung1123

2023-03-13 14:43 UTC, BadaHertz52 commented on src/components/Modals.tsx
> +  type:undefined,
일단, type을 제외한 부분에서 null을 쓴 것은 모달 마다 필요한 것들이 contents를 제외하고는 다 다르더라구요. 
가령 toast 모달에서는 yes/no 버튼이나 close 버튼이 필요없지만 confirm 모달에서는 yes/no 버튼이 필요해요.
그래서  null값으로 잡았고, type는 아직 미정이지 않을까 해서 undefined로 잡았는데 통일감을 위해서 이것도 null 값으로 바꾸는게 나을까요?

2023-03-13 14:45 UTC, BadaHertz52 commented on src/components/Modals.tsx
> +  type:undefined,
> undefined를 쓰는 경우와 null을 쓰는 경우의 차이가 있나요?

type을 제외한 것들은 모달마다 안들어가는 것도 있고 해서 null 값을 잡았고 type은 modal이 없을 수도 있으니 null 값이 나을 것 같네요. 이 부분 수정하겠습니다.

2023-03-13 14:47 UTC, BadaHertz52 commented on src/components/Modals.tsx
> +      {modal.type == undefined &&
> modal.type == undefined와 아닌것인데 ? : 를 이용하는것이 더 간결해보입니다.

아직 alert 만 만들어져서 임시로 이렇게 진행했구요.
차후에 다른 모달들이 만들어지면 ? : 을 사용할 예정입니다

2023-03-13 14:57 UTC, hyunsung1123 approved these changes
타입스크립트 문법 신기하네요 ! 
고생하셨습니다.

2023-03-13 15:31 UTC, BadaHertz52 commented
> 전반적으로 영어 오타가 많습니다. 변수명에도 오타들이 있고 PR 메시지에서도 오타가 많아서 수정 요청드립니다.
 
 오타 수정 완료 했습니다 ! 

> 그리고 모달을 생성한것이 여러개인데 components안에 modal이라는 폴더를 만들고 그 안에 정리하는것이 나중에도 보기 좋아보입니다.

 네

> 현재 봤을 때 Modal간의 관계가 명확히 알기가 어렵습니다.

저는 모달이 다 각자의 독립적인 객체라고 생각했는데 모달 간의 관계가 명확해야하는 이유를 알 수 있을 까요 ? 

> 모달이라는 Base Class를 만들고 다른 모달들이 그것을 가져와 쓰는 형태가 보기 좋아보입니다.  

저는  각각의 모달을 Portals의 child 로  두었는데 창윤님은 class로 모달의 공통된 부분을 만들고 이를 각 모달에 활용해서 각 모달안에서 Portals로 만드는 겟 좋을 것 같다는 것 같다는 의견인 것 같습니다.

각 모달이 모달이라는 것은 같지만 필요로하는 element나 기능들이 다 달라서  공통된 element 라고 해야할까요? 그거는 모달 안에 들어가는 글자들(contents) 만 있더라구요.  toast 모달의 경우에는 2초 후에 자동으로 닫히는 거라 close 버튼이 필요 없고, confirm 모달 이여도 페이지별로 버튼 안에 들어가는 text node가 다 달라서 ... 저는 따로 만드는 게 낫지 않나 생각했습니다. 

만약 창윤님이 제안하신 방법대로 진행한다면 close 버튼이 필요없는 모달의 경우나, Modal에 없는 yes/no 버튼이 필요하다거나 처럼 모달 별로 Modal에서 반환하는  React Element들을 변경하는 방법이 있을까요?

2023-03-13 15:37 UTC, BadaHertz52 commented
> 전반적으로 영어 오타가 많습니다. 변수명에도 오타들이 있고 PR 메시지에서도 오타가 많아서 수정 요청드립니다.
 
 오타 수정 완료 했습니다 ! 

> 그리고 모달을 생성한것이 여러개인데 components안에 modal이라는 폴더를 만들고 그 안에 정리하는것이 나중에도 보기 좋아보입니다.

 네

> 현재 봤을 때 Modal간의 관계가 명확히 알기가 어렵습니다.

저는 모달이 다 각자의 독립적인 객체라고 생각했는데 모달 간의 관계가 명확해야하는 이유를 알 수 있을 까요 ? 

> 모달이라는 Base Class를 만들고 다른 모달들이 그것을 가져와 쓰는 형태가 보기 좋아보입니다.  

저는  각각의 모달을 Portals의 child 로  두었는데 창윤님은 class로 모달의 공통된 부분을 만들고 이를 각 모달에 활용해서 각 모달안에서 Portals로 만드는 겟 좋을 것 같다는 것 같다는 의견인 것 같습니다.

각 모달이 모달이라는 것은 같지만 필요로하는 element나 기능들이 다 달라서  공통된 element 라고 해야할까요? 그거는 모달 안에 들어가는 글자들(contents) 만 있더라구요.  toast 모달의 경우에는 2초 후에 자동으로 닫히는 거라 close 버튼이 필요 없고, confirm 모달 이여도 페이지별로 버튼 안에 들어가는 text node가 다 달라서 ... 저는 따로 만드는 게 낫지 않나 생각했습니다. 

만약 창윤님이 제안하신 방법대로 진행한다면 close 버튼이 필요없는 모달의 경우나, Modal에 없는 yes/no 버튼이 필요하다거나 처럼 모달 별로 Modal에서 반환하는  React Element들을 변경하는 방법이 있을까요?

2023-03-14 04:54 UTC, BadaHertz52 commented
수정 후 다른 ps 올리겠습니다.

2023-03-14 04:54 UTC, closed without merging